// Produces dist/inspect-comment.js: a classic-script IIFE build of the ESM core.
//
// WHY this exists at all: the source is ESM so React and bundlers can import it,
// but ESM cannot be pasted into a browser console and is blocked by CSPs that
// forbid dynamic import(). The console-paste path is the whole reason the tool
// works on sites you do not control, so it gets a real build artifact, committed
// to the repo so using it never requires an install.
//
// TRADEOFF: this is a regex transform, not a parser. That is proportionate for
// one dependency-free file, but it can only handle the export forms actually
// used, so it hard-fails on anything else rather than emitting a broken bundle.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "src", "inspect-comment.js");
const OUT = join(root, "dist", "inspect-comment.js");

const src = await readFile(SRC, "utf8");

if (/^\s*import\s/m.test(src) || /\bimport\s*\(/.test(src) || /import\.meta/.test(src)) {
  throw new Error("build: the core gained an import; the naive bundler cannot handle it.");
}

const body = src
  // `export { a, b };` re-export lists carry no runtime meaning here.
  .replace(/^export\s*\{[^}]*\}\s*;?[ \t]*$/gm, "")
  // `export function foo` / `export const foo` keep the declaration.
  .replace(/^export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)/gm, "");

if (/^\s*export\b/m.test(body)) {
  throw new Error("build: an unhandled `export` form survived the transform.");
}

const out = `/*! inspect-comment - IIFE build, generated by scripts/build.mjs. Edit src/ instead. */
(function () {
"use strict";
${body}
mount();
})();
`;

// Fail loudly here rather than shipping a bundle that throws in the console.
try {
  new Function(out);
} catch (err) {
  throw new Error(`build: generated bundle does not parse: ${err.message}`);
}

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, out, "utf8");

console.log(`built dist/inspect-comment.js (${(out.length / 1024).toFixed(1)} kB)`);
